title: "Anikat Kankaria"
description: "Research in Fluid Dynamics, Turbulence & Nonlinear Physics"

theme: minima

minima:
  skin: dark   # â† enables built-in dark mode

author:
  name: "Anikat Kankaria"

markdown: kramdown

header_pages:
  - index.md
  - research.md

