title: "Anikat Kankaria"
description: "Research in Fluid Dynamics, Turbulence & Nonlinear Physics"

# Theme (GitHub Pages default theme)
theme: minima

# Author Information
author:
  name: "Anikat Kankaria"

# Markdown Processor
markdown: kramdown

# Navigation (pages that appear in the header)
header_pages:
  - index.md
  - research.md
  - publications.md
  - teaching.md
  - contact.md

# URL settings (important for correct links)
url: "https://Anikat31.github.io"
baseurl: ""

# Enable SCSS processing for custom stylesheet
sass:
  style: compressed
